spring:
  application:
    name: pao-gateway
  cloud:
    nacos:
      server-addr: pao-nacos:8848
  config:
    import:
      # 从类路径加载配置文件，后续可以从Nacos配置中心加载
      - 'classpath:routes.yml'
#      - 'nacos:application.yml'

server:
  port: 8080