spring:
  cloud:
    gateway:
      routes:
        - id: pao-order-service
          uri: lb://pao-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: pao-user-service
          uri: lb://pao-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1