# Docker环境特有配置
spring:
  datasource:
    url: jdbc:mysql://pao-db:3306/pao?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: pao-redis
      port: 6379
  ai:
    ollama:
      base-url: http://pao-ollama:11434
      chat:
        options:
          model: gemma3:4b