server:
  port: 8181
  servlet:
    context-path: /api
  ssl:
    certificate: classpath:cert.pem
    certificate-private-key: classpath:key.pem
    enabled: true

spring:
  application:
    name: dongpaopao
  profiles:
    active:
#      - dev
      - docker
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
  ai:
    ollama:
      chat:
        model: gemma3:4b