spring:
  datasource:
    url: jdbc:mysql://pao-db:3306/pao?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: pao-redis
  ai:
    ollama:
      base-url: http://pao-ollama:11434