spring:
  application:
    name: pao-user-service
  cloud:
    nacos:
      discovery:
        server-addr: pao-nacos:8848
  datasource:
    url: jdbc:mysql://pao-db:3306/pao?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
server:
  port: 8888

