CREATE TABLE `t_dispatcher_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `school_id` bigint NOT NULL COMMENT '校区ID',
  `id_card_front` varchar(255) DEFAULT NULL COMMENT '身份证正面',
  `id_card_back` varchar(255) DEFAULT NULL COMMENT '身份证背面',
  `student_card` varchar(255) DEFAULT NULL COMMENT '学生证',
  `approval_status` tinyint DEFAULT 0 COMMENT '审核状态：0-待审核，1-已通过，2-已拒绝',
  `approval_time` datetime DEFAULT NULL COMMENT '审核时间',
  `approval_user` bigint DEFAULT NULL COMMENT '审核人',
  `order_count` int DEFAULT 0 COMMENT '已完成订单数',
  `success_rate` decimal(5,2) DEFAULT 100.00 COMMENT '成功率',
  `last_online_time` datetime DEFAULT NULL COMMENT '最后在线时间',
  `status` tinyint DEFAULT 1 COMMENT '状态：1-在线，0-离线，2-忙碌中',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_id` (`user_id`),
  KEY `idx_school_id` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='跑腿员信息表';