CREATE TABLE `t_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单编号',
  `user_id` bigint NOT NULL COMMENT '下单用户ID',
  `dispatcher_id` bigint DEFAULT NULL COMMENT '跑腿员ID',
  `school_id` bigint NOT NULL COMMENT '校区ID',
  `task_type` tinyint NOT NULL COMMENT '任务类型：1-快递代拿，2-食堂代买，3-代办事务...',
  `pickup_address` varchar(255) DEFAULT NULL COMMENT '取货地址',
  `delivery_address` varchar(255) DEFAULT NULL COMMENT '送货地址',
  `pickup_longitude` decimal(10,6) DEFAULT NULL COMMENT '取货点经度',
  `pickup_latitude` decimal(10,6) DEFAULT NULL COMMENT '取货点纬度',
  `delivery_longitude` decimal(10,6) DEFAULT NULL COMMENT '送货点经度',
  `delivery_latitude` decimal(10,6) DEFAULT NULL COMMENT '送货点纬度',
  `receiver_name` varchar(50) DEFAULT NULL COMMENT '收货人姓名',
  `receiver_phone` varchar(11) DEFAULT NULL COMMENT '收货人电话',
  `weight` decimal(5,2) DEFAULT NULL COMMENT '物品重量（kg）',
  `description` varchar(500) DEFAULT NULL COMMENT '任务描述',
  `reward` decimal(10,2) DEFAULT 0.00 COMMENT '报酬',
  `tips` decimal(10,2) DEFAULT 0.00 COMMENT '小费',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '订单状态：1-待接单，2-已接单，3-已取货，4-已送达，5-已取消',
  `expected_time` datetime DEFAULT NULL COMMENT '期望完成时间',
  `actual_time` datetime DEFAULT NULL COMMENT '实际完成时间',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_no` (`order_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_dispatcher_id` (`dispatcher_id`),
  KEY `idx_school_id` (`school_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';