CREATE TABLE `t_payment_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '支付记录ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `payment_no` varchar(32) NOT NULL COMMENT '支付流水号',
  `user_id` bigint NOT NULL COMMENT '支付用户ID',
  `amount` decimal(10,2) NOT NULL COMMENT '支付金额',
  `payment_type` tinyint DEFAULT 1 COMMENT '支付方式：1-微信，2-支付宝，3-余额',
  `status` tinyint DEFAULT 1 COMMENT '状态：1-待支付，2-支付成功，3-支付失败，4-已退款',
  `transaction_id` varchar(64) DEFAULT NULL COMMENT '第三方交易ID',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
  `refund_reason` varchar(255) DEFAULT NULL COMMENT '退款原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_payment_no` (`payment_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付记录表';